version: '3'
services:
  db:
    image: mongo:4.0.20
    command: mongod --smallfiles
  rocketchat:
    image: rocketchat/rocket.chat
    environment:
      - MONGO_OPLOG_URL=mongodb://db:27017/local
      - ROOT_URL=http://localhost
    links:
      - db
    ports:
      - 3000:3000
  hubot:
    image: rocketchat/hubot-rocketchat
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=test
      - ROCKETCHAT_USER=Hubot
      - ROCKETCHAT_PASSWORD=rzg123456
      - BOT_NAME=Hubot
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
    links:
      - rocketchat:rocketchat
    ports:
      - 3001:8080